### PR TITLE
Authentication: Restrict access to commands after logout

### LINKED ISSUE #199: [PE-D][Tester A] Wrong command format not being caught after logout
If the command `login admin` is run as the first ever command when started, it will prompt me with a "Please Login First" error.

However, if I were to logout with the command `logout login`, and try logging in again with `login admin`, it is inconsistent and no longer gives me the "Please Login First" error, instead opening up the login modal.

For reproducibility, you can try the following trace: `login admin (fails)` -> `login` -> `logout login` -> `login admin`

Below is a screencast of how I reproduced the problem:

<i><video controls><source src="https://raw.githubusercontent.com/DESU-CLUB/ped/main/files/5344ebc3-9c1b-4633-91a6-3390a46200dc.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/DESU-CLUB/ped/main/files/5344ebc3-9c1b-4633-91a6-3390a46200dc.mp4</i>

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: DESU-CLUB/ped#4

### PR DESCRIPTION
**Pull request by reuben-thomas**
Fixes #199, #201. We also refactor the code to improve the use of SLAP.

### CODE REVIEW

**Comment by reuben-thomas** [comment]
I realise that this inadvertently fixes #182 as well.

File: src/main/java/seedu/address/logic/LogicManager.java [hunk 1]
```diff
@@ -125,6 +118,12 @@ public void logUserIn(String accountType) {
         isLoggedIn = true;
     }
 
+    @Override
+    public void logUserOut() {
+        isAdmin = false;
```
Comment (LF1928) [inline src/main/java/seedu/address/logic/LogicManager.java:123]: Looks ok but if we r removing RBAC is isAdmin still relevant?

**Review by LF1928 — APPROVED** [review]
Other than the comment, the rest LGTM

**Review by jonaturn — APPROVED** [review]

File: src/main/java/seedu/address/logic/LogicManager.java (hunk 1 above)
Comment (reuben-thomas) [reply src/main/java/seedu/address/logic/LogicManager.java:123]: Yeap, that change will come from @jonaturn subsequent PR
