### PR TITLE
Update bugs in error messages and remove login in GUI and change status prefix to st/

### LINKED ISSUE #225: [PE-D][Tester B] Specify allowed path in error message for import command
Perhaps change "Full File Path" to specify that relative or absolute paths are acceptable, to be consistent with the UG?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: DengTianle/ped#10

### PR DESCRIPTION
**Pull request by LF1928**
Fixes #225, #224, #220, #185

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
 public class Name {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names should only contain alphanumeric characters and spaces, and it should not be blank.";
```
Comment (gajinkee) [inline src/main/java/seedu/address/model/person/Name.java:13]: Should update that it allows some special characters also `'` , `/` and  '-'.
I changed the regex it in my pr.

**Review by gajinkee — CHANGES_REQUESTED** [review]
LGTM. Some nits to pick.

File: src/main/java/seedu/address/model/tag/Status.java
Comment (reuben-thomas) [inline src/main/java/seedu/address/model/tag/Status.java:1]: A better way to do this would be to enumerate over all possible values of the enum, rather than hard coding the string values.

File: src/main/java/seedu/address/model/person/OrgID.java [hunk 2]
```diff
@@ -10,8 +10,8 @@
 public class OrgID {
     public static final String MESSAGE_CONSTRAINTS = "OrgIDs should only "
             + "be unique numeric values "
-            + ", should be less than 10 digits "
-            + "and it should not be blank";
+            + ", should be less than or equal to 10 digits "
```
Comment (reuben-thomas) [inline src/main/java/seedu/address/model/person/OrgID.java:13]: The same can be said here, it would be better to use the limit value rather than hard code the value 10.

File: src/main/java/seedu/address/logic/commands/SetStatusCommand.java [hunk 3]
```diff
@@ -19,8 +19,8 @@ public class SetStatusCommand extends Command {
     public static final String COMMAND_WORD = "set-status";
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": sets the status of the person identified by the index number\n"
-            + "Parameters: INDEX (must be a positive integer) s/status\n"
-            + "Example: " + COMMAND_WORD + " 1 s/pending_approval";
+            + "Parameters: INDEX (must be a positive integer) st/STATUS\n"
+            + "Example: " + COMMAND_WORD + " 1 st/pending_approval";
```
Comment (reuben-thomas) [inline src/main/java/seedu/address/logic/commands/SetStatusCommand.java:23]: Same can be said here, use the `PREFIX_STATUS` instead of hard coding "st".

**Review by reuben-thomas — CHANGES_REQUESTED** [review]
LGTM! I think this is a good opportunity to stop hard coding values in the error messages. Though since this is not your code its up to you whether you want to fix it, else we can resolve in a separate PR. 

The only serious one not to hardcode in would be the prefixes in `SetStatusCommand.java`

**Comment by LF1928** [comment]
fixes #218 #183

**Review by reuben-thomas — APPROVED** [review]
Looks great! Thanks for improving the code quality as well
