### PR TITLE
Fix bug when using register when logged in as IT staff

### LINKED ISSUE #164: App does not respond to `register` on IT staff account
When using `register` on IT staff account, I get the following error message in the logs:
```
INFO: ----------------[USER COMMAND][register]
Exception in thread "JavaFX Application Thread" java.lang.AssertionError: This is an illegal state. Invalid command words should have caught earlier, due to their absence in the COMMAND_WORDS_ALL array.
        at seedu.address.logic.parser.AddressBookParser.parseCommandIT(AddressBookParser.java:222)
        at seedu.address.logic.LogicManager.execute(LogicManager.java:82)
        at seedu.address.ui.MainWindow.executeCommand(MainWindow.java:221)
        at seedu.address.ui.CommandBox.handleCommandEntered(CommandBox.java:57)
        at seedu.address.ui.CommandBox.lambda$new$0(CommandBox.java:36)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:219)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:178)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2195)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2716)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
        at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:542)
        at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:966)
```

The app continues to run, but does not respond to the command.

### PR DESCRIPTION
**Pull request by LF1928**
Fixes #164

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java [hunk 1]
```diff
@@ -185,6 +185,8 @@ public Command parseCommandIT(String userInput) throws ParseException {
 
         case DeleteCommand.COMMAND_WORD:
 
+        case RegisterCommand.COMMAND_WORD:
```
Comment (reuben-thomas) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java:188]: I think we should come up with a better way to do this in a subsequent PR. The code duplication between both roles makes it easy to write bugs.

**Review by reuben-thomas — APPROVED** [review]
Nicely done, and thanks for updating the images. LGTM!
